### ISSUE TITLE
Is it make a copy on Android?

### ISSUE THREAD

**Issue by dodatw** [KasemJaffer/flutter_absolute_path#12]
Hi,

 I try to use this packages to convert video Uri to AbsolutePath on Android.

input:
content://media/external/video/media/4172
ex:
/data/user/0/com.xxx.xxx/cache/IMG_1615440661326.png

I have few question,

1. Is it original file's path ?
2. I fount the return path have `cache`, and process time very long if I choice big file. It look like make a copy.
3. as example, I input a video uri, but return a .png file.

**Comment by dodatw** [comment]
Note: I am testing on Android 10.

**Comment by selankon** [comment]
Hi, 

It makes a cache copy here: https://github.com/KasemJaffer/flutter_absolute_path/blob/master/android/src/main/kotlin/com/kasem/flutter_absolute_path/FileDirectory.kt#L89

I think the project is discontinued and it have errors on the code.

I'm trying to get the absolute file path on AndroidX and for the moment I didn't get a solution.
